// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Yi42rkyuEiH7dcw8uYPDEMzekXBTHuU',
    appId: '1:761103065292:android:f319c789da7684b1d8e269',
    messagingSenderId: '761103065292',
    projectId: 'studently-123',
    storageBucket: 'studently-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqNk_kAlN-c-tIBNjuwMHmX-pf7bN2Y0c',
    appId: '1:761103065292:ios:f43c97a172baf1f2d8e269',
    messagingSenderId: '761103065292',
    projectId: 'studently-123',
    storageBucket: 'studently-123.firebasestorage.app',
    androidClientId: '761103065292-5nah76vbprn8sl1caaqj226nrba92jgb.apps.googleusercontent.com',
    iosClientId: '761103065292-t9kfulo3ujhdgldalg07i81cm0mvd04h.apps.googleusercontent.com',
    iosBundleId: 'com.studently.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoCiDrwwhsaxX361R2NekzPir0TgJI4iI',
    appId: '1:761103065292:web:f9388cb7e478bc35d8e269',
    messagingSenderId: '761103065292',
    projectId: 'studently-123',
    authDomain: 'studently-123.firebaseapp.com',
    storageBucket: 'studently-123.firebasestorage.app',
    measurementId: 'G-STWMQWECEE',
  );

}